### ISSUE TITLE
Errors while creating the snapshot: ValidateSequenceNumber

### ISSUE THREAD

**Issue by plowsec** [0vercl0k/snapshot#6]
First, let me thank you for the awesome tools!

I tried to use `snapshot` to create a full memory dump for `wtf`. I always ran into this error:

```
kd> p
toto_exe!main+0x292:
0033:00007ff6`3c1c94c2 ff15386b0900    call    qword ptr [toto_exe!_imp_DeviceIoControl (00007ff6`3c260000)]
kd> .load C:\Users\testq\Downloads\snapshot\snapshot.dll
kd> !snapshot c:\foo
[snapshot] Dumping the CPU state into c:\foo\state.22621.1.amd64fre.ni_release.220506-1250.20240320_1426\regs.json..
[snapshot] Dumping the memory state into c:\foo\state.22621.1.amd64fre.ni_release.220506-1250.20240320_1426\mem.dmp..
Creating c:\\foo\\state.22621.1.amd64fre.ni_release.220506-1250.20240320_1426\\mem.dmp - 

Press ctrl-c (cdb, kd, ntsd) or ctrl-break (windbg) to abort symbol loads that take too long.
Run !sym noisy before .reload to track down problems loading symbols.

Full memory range dump
0% written.
ValidateSequenceNumber: Sequence number too far ahead for validation.
Wrote 62.8 MB in 38 sec.
The average transfer rate was 1.7 MB/s.
Dump successfully written
[snapshot] Done!
```

However the dump is not valid (only 62.8MB written) and is not accepted by `wtf`:

```
 ..\wtf.exe fuzz --backend=bochscpu --name blah --limit 10000000
Initializing the debugger instance.. (this takes a bit of time)
OpenDumpFile(state\mem.dmp) failed with hr=-0x7ff8ffa9 # error code 87?
```

I have tried several times, and I sometimes get different errors:

```
kd> !snapshot c:\foo
[snapshot] Dumping the CPU state into c:\foo\state.22621.1.amd64fre.ni_release.220506-1250.20240320_1431\regs.json..
[snapshot] Dumping the memory state into c:\foo\state.22621.1.amd64fre.ni_release.220506-1250.20240320_1431\mem.dmp..
Creating c:\\foo\\state.22621.1.amd64fre.ni_release.220506-1250.20240320_1431\\mem.dmp - Full memory range dump
0% written.
ValidateKdPacket: Invalid packet leader. Expected 0x30303030, received 0x69696969.
ValidateKdPacket: Invalid packet leader. Expected 0x30303030, received 0x69696969.
ValidateKdPacket: Invalid packet leader. Expected 0x30303030, received 0x69696969.
ValidateKdPacket: Invalid packet leader. Expected 0x30303030, received 0x69696969.
ValidateKdPacket: Invalid packet leader. Expected 0x30303030, received 0x69696969.
Wrote 512.0 KB in 2 sec.
The average transfer rate was 256.1 KB/s.
Dump successfully written
[snapshot] Done!
```

I don't think those are bugs in `snapshot` but my setup must be wrong. Could you find errors in my setup or give more details about yours?

1. Userland app with `system("PAUSE");` and then  `__debugbreak();` just before DeviceIoControl
2. I open toto.exe inside the guest
3. Windbg attached to the guest's kernel, I switch to toto.exe's context with `.process /p /r <EPROCESS>`
4. On the guest, I press ente to unpause toto.exe, this trigger `__debugbreak();`
5. In Windbg I step until the call to DeviceIoControl
6. Load snapshot.dll
7. Try to snapshot, fail, repeat. 

My setup:

* Host and guest: Windows 11 23h2

* Guest runs inside VMWare.

* Windbg 1.2402.24001.0

Network debugging for kd
```
bcdedit /debug on
bcdedit /dbgsettings net hostip:172.16.9.13 port:50420 nodhcp
```

I also tried over Serial but it takes too long (2h for 16MB).

**Comment by 0vercl0k** [comment]
Thanks a lot for the kind words & taking the time to file a detailed issue - you made my day 🙏

Okay so I've heard a lot of people saying they are not able to acquire kernel crash dumps when VMWare is used as the hypervisor unfortunately. I personally have never tried as I am not a user, but you're not the first person encountering issue with it.

One 'easy' fix would be to use Hyper-V for that VM but that's basically the only recommendation I have. I am also not sure if there's some trick or hack to make taking crash-dump works on VMWare either :-/

Other than that, your setup looks fine to me - nothing wrong there :)

Let me know how this goes.

Cheers

**Comment by 0vercl0k** [comment]
I've helped out @plowsec offline and my understanding is we figured out how to get past this. Closing but feel free to re-open if I missed anything.

Cheers

**Comment by plowsec** [comment]
Indeed and some undefinite amount of beers were promised after getting all this help ^^. 


If anyone runs into the same issues, here are a few notes (I'll write something more detailed in a blog post):

* Switching to a Hyper-V VM in order to make the snapshot, bypasses this issue
* Don't forget to replace the 4 WinDbg DLLs shipped with WTF with your current one if your WinDbg is newer (otherwise same error as https://github.com/0vercl0k/wtf/issues/195)
* Fixed the offsets for ExGenRandom for Windows 11 23h2 like this:


```
  const Gva_t ExGenRandom = Gva_t(g_Dbg.GetSymbol("nt!ExGenRandom") + 0xf5+3);
  if ((g_Backend->VirtRead4(ExGenRandom - Gva_t(3)) & 0x00FFFFFF) != 0xf2c70f) {
    fmt::print("It seems that nt!ExGenRandom's code has changed, update the "
               "offset!\n");
    return false;
  }
  ```
    
  * Disabled the pagefile (thx @0vercl0k) to fix the error `Failed to translate GVA 0xfffff8040d67cfe0, skipping..`
  
  And now we're happy everything works :)

**Comment by 0vercl0k** [comment]
Thank you for documenting the steps!
